import React, { useEffect, useState } from "react";
import { collection, getDocs } from "firebase/firestore";
import { db } from "../firebase";

function Insights() {
  const [insights, setInsights] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");

  useEffect(() => {
    const fetchInsights = async () => {
      try {
        const snap = await getDocs(collection(db, "user_seasonal_insights"));
        const data = snap.docs.map((doc) => ({ id: doc.id, ...doc.data() }));
        // sort newest first
        data.sort((a, b) => {
          const aTime = a.savedAt?.toDate ? a.savedAt.toDate() : new Date(a.savedAt);
          const bTime = b.savedAt?.toDate ? b.savedAt.toDate() : new Date(b.savedAt);
          return bTime - aTime;
        });
        setInsights(data);
      } catch (err) {
        console.error("Error fetching insights:", err);
      }
      setLoading(false);
    };
    fetchInsights();
  }, []);

  const filtered = insights.filter((i) => {
    const q = search.toLowerCase();
    return (
      i.userEmail?.toLowerCase().includes(q) ||
      i.location?.toLowerCase().includes(q) ||
      i.insightContext?.toLowerCase().includes(q)
    );
  });

  const formatDate = (val) => {
    if (!val) return "N/A";
    const d = val?.toDate ? val.toDate() : new Date(val);
    return d.toLocaleString();
  };

  const handleDelete = async (id) => {
    if (!window.confirm("Delete this insight?")) return;
    const { deleteDoc, doc } = await import("firebase/firestore");
    await deleteDoc(doc(db, "seasonal_insights", id));
    setInsights((prev) => prev.filter((i) => i.id !== id));
  };

  if (loading) return <div className="loading-screen">Loading insights...</div>;

  return (
    <div className="page-container">
      <div className="page-header">
        <div>
          <div className="page-title">🌱 User Seasonal Insights Logs</div>
          <div className="page-subtitle">Review seasonal insights generated by users</div>
        </div>
        <div className="page-stats">
          <div className="page-stat-box">{insights.length}<span>Total</span></div>
        </div>
      </div>

      <input
        className="search-input"
        placeholder="Search by User, Email, Location or Context..."
        value={search}
        onChange={(e) => setSearch(e.target.value)}
      />

      <div className="table-card">
        <table className="data-table">
          <thead>
            <tr>
              <th>USER</th>
              <th>LOCATION</th>
              <th>TEMPERATURE</th>
              <th>INSIGHT CONTEXT</th>
              <th>SAVED ON</th>
              <th>ACTION</th>
            </tr>
          </thead>
          <tbody>
            {filtered.length === 0 ? (
              <tr><td colSpan={6} style={{ textAlign: "center", padding: "2rem", color: "#888" }}>No insights found</td></tr>
            ) : (
              filtered.map((item) => (
                <tr key={item.id}>
                  <td>
                    <div style={{ fontWeight: 600 }}>{item.userName || item.userEmail?.split("@")[0] || "Unknown"}</div>
                    <div style={{ fontSize: "0.78rem", color: "#888" }}>{item.userEmail || "—"}</div>
                  </td>
                  <td>{item.location || "N/A"}</td>
                  <td>{item.temperature ? `${item.temperature}°C` : "N/A"}</td>
                  <td>
                    <div style={{
                      background: "#f0fdf4",
                      border: "1px solid #bbf7d0",
                      borderRadius: 6,
                      padding: "6px 10px",
                      fontSize: "0.82rem",
                      maxWidth: 260,
                      lineHeight: 1.4
                    }}>
                      {item.insightContext || "—"}
                    </div>
                  </td>
                  <td style={{ fontSize: "0.82rem" }}>{formatDate(item.savedAt)}</td>
                  <td>
                    <button
                      onClick={() => handleDelete(item.id)}
                      style={{
                        background: "none", border: "none", cursor: "pointer",
                        fontSize: "1.1rem", color: "#e53935"
                      }}
                      title="Delete"
                    >🗑️</button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default Insights;